### ISSUE TITLE
更新版本后无法初始化

### ISSUE THREAD

**Issue by libiaoliang** [Archeb/YOUChat_Proxy#16]
![image](https://github.com/user-attachments/assets/ca82ac86-2143-453b-ae24-c8fc87241a9d)
原来用的版本大概是两个月前的旧版，一直能用，只是经常404需要换IP，今天发现换IP次数尤其频繁后便更新到了新版，但是更新新版后按照提示填入了cookie，在start.bat里填入了http://127.0.0.1:7890后，打开发现一直加载，加载很长时间后会提示图片中的错误，回退到老版本后，反复操作了几次都能够正常初始化和运行，证明不是网络问题，再次更新到新版本后，操作数次，都是会加载特别特别久，然后提示这个错误

**Comment by libiaoliang** [comment]
我可能是在6月末还是七月初的时候更新过当时的新版本，当时的新版本都是能够正常初始化和运行的，用的和现在相同的梯子，当时是我对比测试发现，老版本可以随便破限的地方新版本都不行，便退回到了老版本

**Comment by Archeb** [comment]
从图上看是连不上 npm 导致依赖安装失败，需要挂一个全局梯子再运行 start.bat

**Comment by libiaoliang** [comment]
> 不

一直是全局，我尝试了很多次，回退旧版本后重新配置，每次实验网络都正常，但是立刻切换到新版本重新配置，便会一直加载然后报错，试了多次也切换了很多vpn一直不行

**Comment by Archeb** [comment]
但是这个确实是你没有安装成功依赖，你上网找一下怎么换 npm 源之类的吧
