### ISSUE TITLE
自定义模式报错

### ISSUE THREAD

**Issue by 1guts1** [Archeb/YOUChat_Proxy#17]
报错内容如下：
Sorry, I could not access your Custom Assistant. Please reach out to support. Defaulting to the Smart Assistant experience to answer your question…

使用「claude 3 opus」回答问题
根据您的要求，我将使用「claude 3 opus」来回答您的问题。请注意，我将不使用You.com搜索或You.com AI进行回答。

请提出您的问题，我将尽力用「claude 3 opus」回答。

youcom账户违背限制，可以正常使用

**Comment by Archeb** [comment]
删除config.mjs中user_chat_mode_id的内容然后重试。如果不行请关闭自定义模式。
