### ISSUE TITLE
自定义会话不会自动创建模型

### ISSUE THREAD

**Issue by YIWANG-sketch** [Archeb/YOUChat_Proxy#19]
如果config里没有保存有自定义模型时去请求会出现`抱歉，我无法满足该请求。请求结束`
![image](https://github.com/user-attachments/assets/03d135db-40bb-49df-aa8d-50e8286c226f)

**Comment by Archeb** [comment]
根据第六行是尝试创建了但是失败了，我看看。

**Comment by Archeb** [comment]
YOU那边换API端点了，已修复

**Comment by YIWANG-sketch** [comment]
然后我有个想法是，请求时自动在自定义会话和非自定义会话中来回切换使用，会不会能够减少unusual的触发

**Comment by Archeb** [comment]
感觉还是把这个切换留给用户自己比较好，可以在文档里提一下。

**Comment by YIWANG-sketch** [comment]
可以加个开关，我先实践下可不可行，没用就算了
