### ISSUE TITLE
难顶，账号被封

### ISSUE THREAD

**Issue by lys623** [Archeb/YOUChat_Proxy#9]
![image](https://github.com/Archeb/YOUChat_Proxy/assets/4364314/49c66961-b35a-4387-97a2-6a09cffc89e7)

**Comment by Archeb** [comment]
用得太多了，过几个小时到一天就会恢复。这种问题与本项目无关。

**Comment by lys623** [comment]
> 用得太多了，过几个小时到一天就会恢复。这种问题与本项目无关。

知道哪里有不限制请求量的3.5吗？
